"""migracion_inicial

Revision ID: f9ac89dee0cb
Revises: 
Create Date: 2026-09-23 23:18:33.144075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ac89dee0cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('habitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=100), nullable=False),
    sa.Column('frecuencia_objetivo', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'nombre_normalizado', name='uq_usuario_habito_nombre')
    )
    op.create_index(op.f('ix_habitos_id'), 'habitos', ['id'], unique=False)
    op.create_index(op.f('ix_habitos_nombre_normalizado'), 'habitos', ['nombre_normalizado'], unique=False)
    op.create_index(op.f('ix_habitos_usuario_id'), 'habitos', ['usuario_id'], unique=False)
    op.create_table('registros_habitos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habito_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['habito_id'], ['habitos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habito_id', 'fecha', name='uq_habito_fecha_registro')
    )
    op.create_index(op.f('ix_registros_habitos_fecha'), 'registros_habitos', ['fecha'], unique=False)
    op.create_index(op.f('ix_registros_habitos_habito_id'), 'registros_habitos', ['habito_id'], unique=False)
    op.create_index(op.f('ix_registros_habitos_id'), 'registros_habitos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registros_habitos_id'), table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_habito_id'), table_name='registros_habitos')
    op.drop_index(op.f('ix_registros_habitos_fecha'), table_name='registros_habitos')
    op.drop_table('registros_habitos')
    op.drop_index(op.f('ix_habitos_usuario_id'), table_name='habitos')
    op.drop_index(op.f('ix_habitos_nombre_normalizado'), table_name='habitos')
    op.drop_index(op.f('ix_habitos_id'), table_name='habitos')
    op.drop_table('habitos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
